name: deploy backend to EC2 instance
on:
  push:
    branches:
      - deploy-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Execute pull scripts on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: sudo -S su -c "source run-server.sh"
